networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt/live/euro-dance.org/fullchain.pem:/etc/letsencrypt/live/euro-dance.org/fullchain.pem:ro'
      - '/etc/letsencrypt/live/euro-dance.org/privkey.pem:/etc/letsencrypt/live/euro-dance.org/privkey.pem:ro'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build: 
      context: ./server
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi_db
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./server/public/uploads:~/ecds/server/public/uploads
    networks:
      - dev
    depends_on:
      - postgres

  frontend:
    build:
      context: ./client
    networks:
      - dev

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  postgres_data:
  strapi_uploads:
