version: '3.8'

networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt/live/euro-dance.org/fullchain.pem:/etc/letsencrypt/live/euro-dance.org/fullchain.pem:ro'
      - '/etc/letsencrypt/live/euro-dance.org/privkey.pem:/etc/letsencrypt/live/euro-dance.org/privkey.pem:ro'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build: 
      context: ./server
    networks:
      - dev

  frontend:
    build:
      context: ./client
    networks:
      - dev
