networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt/live/euro-dance.org/fullchain.pem:/etc/letsencrypt/live/euro-dance.org/fullchain.pem:ro'
      - '/etc/letsencrypt/live/euro-dance.org/privkey.pem:/etc/letsencrypt/live/euro-dance.org/privkey.pem:ro'
      - '/var/www/certbot:/var/www/certbot'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build: 
      context: ./server
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: 185.25.117.139
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi_db
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      STORAGE_URL: https://d0c7f715738e1445.cdn.express
    volumes:
      - ./server/public/uploads:/srv/app/public/uploads
    networks:
      - dev

  frontend:
    build:
      context: ./client
    networks:
      - dev
  
  certbot:
    image: certbot/certbot
    volumes:
      - '/etc/letsencrypt:/etc/letsencrypt'
      - '/var/www/certbot:/var/www/certbot'
    entrypoint: >
      sh -c '
      trap exit TERM;
      while :; do
        certbot renew --webroot -w /var/www/certbot;
        sleep 12h & wait $!;
      done'
    networks:
      - dev

volumes:
  postgres_data:
